%General Mission Analysis Tool(GMAT) Script
%Created: 2026-03-23 14:10:09


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
DefaultSC.DateFormat = TAIModJulian;
DefaultSC.Epoch = '21545';
DefaultSC.CoordinateSystem = EarthMJ2000Eq;
DefaultSC.DisplayStateType = Cartesian;
DefaultSC.X = 7100;
DefaultSC.Y = 0;
DefaultSC.Z = 1300;
DefaultSC.VX = 0;
DefaultSC.VY = 7.35;
DefaultSC.VZ = 1;
DefaultSC.DryMass = 850;
DefaultSC.Cd = 2.2;
DefaultSC.Cr = 1.8;
DefaultSC.DragArea = 15;
DefaultSC.SRPArea = 1;
DefaultSC.SPADDragScaleFactor = 1;
DefaultSC.SPADSRPScaleFactor = 1;
DefaultSC.AtmosDensityScaleFactor = 1;
DefaultSC.ExtendedMassPropertiesModel = 'None';
DefaultSC.NAIFId = -10000001;
DefaultSC.NAIFIdReferenceFrame = -9000001;
DefaultSC.OrbitColor = Red;
DefaultSC.TargetColor = Teal;
DefaultSC.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
DefaultSC.CdSigma = 1e+70;
DefaultSC.CrSigma = 1e+70;
DefaultSC.Id = 'SatId';
DefaultSC.Attitude = CoordinateSystemFixed;
DefaultSC.SPADSRPInterpolationMethod = Bilinear;
DefaultSC.SPADSRPScaleFactorSigma = 1e+70;
DefaultSC.SPADDragInterpolationMethod = Bilinear;
DefaultSC.SPADDragScaleFactorSigma = 1e+70;
DefaultSC.AtmosDensityScaleFactorSigma = 1e+70;
DefaultSC.ModelFile = 'aura.3ds';
DefaultSC.ModelOffsetX = 0;
DefaultSC.ModelOffsetY = 0;
DefaultSC.ModelOffsetZ = 0;
DefaultSC.ModelRotationX = 0;
DefaultSC.ModelRotationY = 0;
DefaultSC.ModelRotationZ = 0;
DefaultSC.ModelScale = 1;
DefaultSC.AttitudeDisplayStateType = 'Quaternion';
DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
DefaultSC.EulerAngleSequence = '321';

Create Spacecraft Spacecraft1;
Spacecraft1.DateFormat = TAIModJulian;
Spacecraft1.Epoch = '21545';
Spacecraft1.CoordinateSystem = EarthMJ2000Eq;
Spacecraft1.DisplayStateType = Cartesian;
Spacecraft1.X = -7368.038574853538;
Spacecraft1.Y = -7231.584293256432;
Spacecraft1.Z = -148.523707822187;
Spacecraft1.VX = 4.126512186315761;
Spacecraft1.VY = -3.956371322777358;
Spacecraft1.VZ = -0.490613661500991;
Spacecraft1.DryMass = 850;
Spacecraft1.Cd = 2.2;
Spacecraft1.Cr = 1.8;
Spacecraft1.DragArea = 15;
Spacecraft1.SRPArea = 1;
Spacecraft1.SPADDragScaleFactor = 1;
Spacecraft1.SPADSRPScaleFactor = 1;
Spacecraft1.AtmosDensityScaleFactor = 1;
Spacecraft1.ExtendedMassPropertiesModel = 'None';
Spacecraft1.NAIFId = -10001001;
Spacecraft1.NAIFIdReferenceFrame = -9001001;
Spacecraft1.OrbitColor = Green;
Spacecraft1.TargetColor = LightGray;
Spacecraft1.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
Spacecraft1.CdSigma = 1e+70;
Spacecraft1.CrSigma = 1e+70;
Spacecraft1.Id = 'SatId';
Spacecraft1.Attitude = CoordinateSystemFixed;
Spacecraft1.SPADSRPInterpolationMethod = Bilinear;
Spacecraft1.SPADSRPScaleFactorSigma = 1e+70;
Spacecraft1.SPADDragInterpolationMethod = Bilinear;
Spacecraft1.SPADDragScaleFactorSigma = 1e+70;
Spacecraft1.AtmosDensityScaleFactorSigma = 1e+70;
Spacecraft1.ModelFile = 'aura.3ds';
Spacecraft1.ModelOffsetX = 0;
Spacecraft1.ModelOffsetY = 0;
Spacecraft1.ModelOffsetZ = 0;
Spacecraft1.ModelRotationX = 0;
Spacecraft1.ModelRotationY = 0;
Spacecraft1.ModelRotationZ = 0;
Spacecraft1.ModelScale = 1;
Spacecraft1.AttitudeDisplayStateType = 'Quaternion';
Spacecraft1.AttitudeRateDisplayStateType = 'AngularVelocity';
Spacecraft1.AttitudeCoordinateSystem = EarthMJ2000Eq;
Spacecraft1.EulerAngleSequence = '321';

%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 0;
DefaultProp_ForceModel.GravityField.Earth.Order = 0;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
DefaultOrbitView.SolverIterations = Current;
DefaultOrbitView.UpperLeft = [ 0.002941176470588235 0 ];
DefaultOrbitView.Size = [ 0.5 0.4099099099099099 ];
DefaultOrbitView.RelativeZOrder = 153;
DefaultOrbitView.Maximized = false;
DefaultOrbitView.Add = {Spacecraft1, Earth};
DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.DrawObject = [ true true ];
DefaultOrbitView.DataCollectFrequency = 1;
DefaultOrbitView.UpdatePlotFrequency = 50;
DefaultOrbitView.NumPointsToRedraw = 0;
DefaultOrbitView.ShowPlot = true;
DefaultOrbitView.MaxPlotPoints = 20000;
DefaultOrbitView.ShowLabels = true;
DefaultOrbitView.ViewPointReference = Earth;
DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
DefaultOrbitView.ViewDirection = Earth;
DefaultOrbitView.ViewScaleFactor = 1;
DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.ViewUpAxis = Z;
DefaultOrbitView.EclipticPlane = Off;
DefaultOrbitView.XYPlane = On;
DefaultOrbitView.WireFrame = Off;
DefaultOrbitView.Axes = On;
DefaultOrbitView.Grid = Off;
DefaultOrbitView.SunLine = Off;
DefaultOrbitView.UseInitialView = On;
DefaultOrbitView.StarCount = 7000;
DefaultOrbitView.EnableStars = On;
DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
DefaultGroundTrackPlot.SolverIterations = Current;
DefaultGroundTrackPlot.UpperLeft = [ 0.002941176470588235 0.4144144144144144 ];
DefaultGroundTrackPlot.Size = [ 0.5 0.4099099099099099 ];
DefaultGroundTrackPlot.RelativeZOrder = 121;
DefaultGroundTrackPlot.Maximized = false;
DefaultGroundTrackPlot.Add = {Spacecraft1};
DefaultGroundTrackPlot.DataCollectFrequency = 1;
DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
DefaultGroundTrackPlot.NumPointsToRedraw = 0;
DefaultGroundTrackPlot.ShowPlot = true;
DefaultGroundTrackPlot.MaxPlotPoints = 20000;
DefaultGroundTrackPlot.CentralBody = Earth;
DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';

Create ReportFile ReportFile1;
ReportFile1.SolverIterations = Current;
ReportFile1.UpperLeft = [ 0.2770588235294117 0.05630630630630631 ];
ReportFile1.Size = [ 0.5988235294117648 0.7972972972972973 ];
ReportFile1.RelativeZOrder = 139;
ReportFile1.Maximized = false;
ReportFile1.Filename = 'ReportFile1.txt';
ReportFile1.Precision = 16;
ReportFile1.Add = {Spacecraft1.Earth.C3Energy, Spacecraft1.Earth.ECC, Spacecraft1.Earth.Energy};
ReportFile1.WriteHeaders = true;
ReportFile1.LeftJustify = On;
ReportFile1.ZeroFill = Off;
ReportFile1.FixedWidth = true;
ReportFile1.Delimiter = ' ';
ReportFile1.ColumnWidth = 23;
ReportFile1.WriteReport = true;
ReportFile1.AppendToExistingFile = false;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(Spacecraft1) {Spacecraft1.ElapsedSecs = 100000.0};
